Update staging.yml

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -7,7 +7,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Deploy NESTJS app
+      - name: Deploy UcabProfile Frontend
         uses: appleboy/ssh-action@v0.1.2
         with:
           host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
@@ -18,10 +18,17 @@ jobs:
             cd /var/www 
             cd ER-frontend-staging
             git checkout staging
-            git pull
-            npm install
+            git pull || exit 1
+            npm install || exit 1
 
             # Agrega comandos para liberar recursos o archivos bloqueados
-            sudo rm -rf dist
-            npm run build
+            chmod -R 777 dist || exit 1
+            rm -rf dist || exit 1
+            # Ejecuta npm run build y verifica el resultado
+            if npm run build; then
+              echo 'Build successful'
+            else
+              echo 'Build failed'
+              exit 1
+            fi
             echo 'Repository already exists previously, pulling changes'
